# Generated by Django 2.0.6 on 2018-06-27 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('symptoms', models.TextField(blank=True, max_length=500, verbose_name='Sintomas')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Dose')),
                ('date', models.DateTimeField(verbose_name='Data/Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('specialty', models.CharField(max_length=50, verbose_name='Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Elderly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('allergies', models.ManyToManyField(blank=True, to='sharedcare.Allergy', verbose_name='Alergias')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('meal_type', models.CharField(choices=[('CM', 'Café da Manhã'), ('LA', 'Lanche'), ('AL', 'Almoço'), ('JA', 'Janta'), ('CE', 'Ceia')], max_length=2, verbose_name='Tipo de refeição')),
                ('date', models.DateTimeField(verbose_name='Data/Hora')),
                ('foods', models.ManyToManyField(blank=True, to='sharedcare.Food', verbose_name='Alimentos')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descrição da consulta')),
                ('date', models.DateTimeField(verbose_name='Data/Hora')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='sharedcare.Doctor', verbose_name='Médico')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='sharedcare.Elderly', verbose_name='Idoso')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(verbose_name='Data de início')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('frequency', models.PositiveIntegerField(verbose_name='Frequência (horas)')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedcare.Medicine', verbose_name='Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='elderly',
            name='caretaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedcare.UserProfile', verbose_name='Cuidador'),
        ),
        migrations.AddField(
            model_name='elderly',
            name='meals',
            field=models.ManyToManyField(blank=True, to='sharedcare.Meal', verbose_name='Refeições'),
        ),
        migrations.AddField(
            model_name='elderly',
            name='medical_appointments',
            field=models.ManyToManyField(related_name='person', through='sharedcare.MedicalAppointment', to='sharedcare.Doctor', verbose_name='Consultas médicas'),
        ),
        migrations.AddField(
            model_name='elderly',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='sharedcare.ConsumedMedicine', verbose_name='Medicamentos injeridos'),
        ),
        migrations.AddField(
            model_name='elderly',
            name='prescribed_medicine',
            field=models.ManyToManyField(blank=True, to='sharedcare.Prescription', verbose_name='Medicamentos prescritos'),
        ),
        migrations.AddField(
            model_name='consumedmedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedcare.Medicine', verbose_name='Medicamento'),
        ),
    ]
