# Generated by Django 2.0.6 on 2018-06-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='consumedmedicine',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='elderly',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='medicalappointment',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['startDate']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['birth_date']},
        ),
    ]
