# Generated by Django 2.0.6 on 2018-06-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedcare', '0002_auto_20180628_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_type',
            field=models.CharField(blank=True, choices=[('V', 'Visitante'), ('C', 'Cuidador'), ('F', 'Familiar')], default='V', max_length=1, null=True, verbose_name='Tipo de acesso'),
        ),
    ]
