# Generated by Django 2.0.6 on 2018-06-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedcare', '0003_userprofile_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='elderlies',
            field=models.ManyToManyField(blank=True, to='sharedcare.Elderly', verbose_name='Familiares'),
        ),
    ]
